version: "3"

services:
    nginx:
        ports:
            - "5000:80"
    server:
        build:
            
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=devolopment
        command: yarn ts-dev