version: "3"

services: 
    nginx:
        ports:
            - "80:80"
    server:
        build:
            context: .
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
        command: yarn start