version: "3"

services:
    nginx:
        image: nginx:stable-alpine 
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports: 
            - "5000:80"
    server:
        build: .
        volumes: 
            - ./:/app
            - ./app/node_modules
        environment: 
            - NODE_PORT=${port}
            - DB_URL= ${DB_URL}
        
    postgres-db:
        image: postgres:13.2-alpine
        environment: 
            POSTGRES_PASSWORD: ${PG_PASS}
        volumes: 
            - pg-data:/var/lib/postgresql/data
    redis:
        image: redis:6.2.3-alpine
        volumes: 
            - redis-data:/usr/local/etc/redis
volumes: 
    pg-data:
    redis-data: